# Generated by Django 2.0.4 on 2018-04-20 01:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0002_auto_20180419_0000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyentry',
            name='daily_entry_id',
        ),
        migrations.AddField(
            model_name='dailyentry',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
