# Generated by Django 2.0.4 on 2018-04-20 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0003_auto_20180420_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyentry',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
