# Generated by Django 2.0.4 on 2018-04-23 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0007_auto_20180423_0329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weeklygoal',
            old_name='weekly_goal',
            new_name='goal_type',
        ),
        migrations.RemoveField(
            model_name='weeklyentry',
            name='week_end',
        ),
        migrations.AddField(
            model_name='weeklygoal',
            name='is_complete',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
    ]
